name: Package PowerShell App - Feature Branch

on:
  push:
    branches:
      - Feature1
    paths:
      - 'Scripts/*'
      - 'ScriptManager.ps1'
      - 'modules/*'
      - 'UnitTests/*'
      - .github/workflows/workflow.yml
      - 'package.psd1'
      - 'icon.ico'

jobs:
  unittest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pester
        shell: pwsh
        run: |
          if (-not (Get-Module -ListAvailable -Name Pester)) {
              Install-Module -Name Pester -Force -SkipPublisherCheck
          }
