name: Package PowerShell App - DEV Branch

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'Scripts/**/*.ps1'
      - 'ScriptManager/ScriptManager.ps1'
      - 'UnitTests/**/*.ps1'
      - .github/workflows/dev-workflow.yml
      - 'ScriptManager/package.psd1'
  push:
    branches:
      - dev
    paths:
      - 'ScriptManager/ScriptManager.ps1'
      - .github/workflows/dev-workflow.yml
      - 'ScriptManager/package.psd1'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: Install PowerShellProTools
        shell: pwsh
        run: |
          if (-not (Get-Module -ListAvailable -Name PowerShellProTools)) {
              Install-Module -Name PowerShellProTools -Force
          }
          Import-Module PowerShellProTools

      - name: Start Script Watcher
        shell: pwsh
        run: |
          .\ScriptManager\Watch-ScriptsFolder.ps1
          
      - name: Build Executable
        shell: pwsh
        run: |
          Copy-Item -Path ".\ScriptManager\icon.ico" -Destination "C:\\icon.ico"
          Merge-Script -ConfigFile '.\ScriptManager\package.psd1' -Verbose   

      - name: Commit and Push Executable
        shell: pwsh
        run: |        
          if (Test-Path 'ScriptManager.exe') {
              git config --global user.name "GitHub Action"
              git config --global user.email "action@github.com"
              git checkout dev
              Copy-Item -Path "ScriptManager.exe" -Destination "ScriptManager\ScriptManager.exe"
              git add ScriptManager\ScriptManager.exe
              git add ScriptManager\ScriptManager.ps1
              git commit -m "Add ScriptManager.exe" || Write-Host "Nothing to commit"
              git push origin dev || Write-Host "Failed to push changes"
          } else {
              Write-Host "Executable not found"
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
