name: Package PowerShell App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.3
        with:
          script: |
            Install-Module -Name PowerShellProTools -Force
            Import-Module PowerShellProTools
            Merge-Script -ConfigFile 'package.psd1' -Verbose

      - name: Commit and Push Executable
        run: |
          cd out
          
          if (Test-Path 'AutomationTool.exe') {
              # Stage the file
              git add AutomationTool.exe
              
              # Commit the changes
              git commit -m "Add AutomationTool.exe"
              
              # Push the changes using the GITHUB_TOKEN
              git push
          } else {
              Get-Location
              ls
          }
        env:
          # Use the GITHUB_TOKEN for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
