name: Package PowerShell App

on:
  push:
    branches:
      - master
    paths:
      - 'Scripts/'
      - 'AutomationTool.ps1'
      - 'modules/'
      - 'UnitTests/'
      - .github/workflows/main.yml

jobs:
  unittest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Run Unit Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path .\UnitTests\ -EnableExit
          if ($LASTEXITCODE -ne 0) {
              throw "Unit tests failed"
          }
        
  build:
    runs-on: windows-latest
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PowerShellProTools
        uses: Amadevus/pwsh-script@v2.0.3
        with:
          script: |
            Install-Module -Name PowerShellProTools -Force
            Import-Module PowerShellProTools
            Move-Item -Path "icon.ico" -Destination "C:\\icon.ico"
            Merge-Script -ConfigFile 'package.psd1' -Verbose

      - name: Commit and Push Executable
        run: |        
          if (Test-Path 'AutomationTool.exe') {
              git config --global user.name "GitHub Action"
              git config --global user.email "action@github.com"
              git add AutomationTool.exe
              git commit -m "Add AutomationTool.exe"
              git push
          } else {
              Write-Host "Executable not found"
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
