name: Package PowerShell App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: powershell/powershell@7.4.0  # Specify a valid version

      - name: Install PowerShell Pro Tools Module
        run: |
          Install-Module -Name PowerShellProTools -Force

      - name: Package Script
        run: |
          Import-Module PowerShellProTools
          Merge-Script -ConfigFile 'c:\AutomationProject\package.psd1' -Verbose
