# This is a GitHub Actions workflow file for running unit tests on the Low Free Space script.
name: Performance Issue Unit Tests
on:
  push:
    branches:
      - 'PerformanceIssue/**'
    paths:
      - 'Scripts/PerformanceIssue/PerformanceIssue.ps1'
      - 'UnitTests/PerformanceIssue/PerformanceIssue.Tests.ps1'
      - .github/workflows/PerformanceIssue.yml

jobs:
  unittest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pester
        shell: pwsh
        run: |
          $PesterModule = Get-Module -ListAvailable -Name Pester
          if ($PesterModule) {
              if ($PesterModule.Version -eq "5.7.1") {
                  Write-Host "Pester version 5.7.1 is installed."
                  Import-Module Pester -RequiredVersion 5.7.1
              } else {
                  Write-Host "Pester is installed, but the version is $($PesterModule.Version).  Expected version 5.7.1."
                  Write-Host "Installing Pester version 5.7.1..."
                  Install-Module -Name Pester -RequiredVersion 5.7.1 -Force -SkipPublisherCheck
                  Import-Module Pester -RequiredVersion 5.7.1
              }
          } else {
              Write-Host "Pester is not installed."
          }

      - name: Run Unit Tests
        shell: pwsh
        run: |
          Get-ChildItem -Path ".\UnitTests\PerformanceIssue" -Filter *.ps1 -Recurse | ForEach-Object { . $_.FullName }