name: Package PowerShell App

on:
  push:
    branches:
      - master
    paths:
      - 'Scripts/*'
      - 'ScriptManager2.ps1'
      - 'modules/*'
      - 'UnitTests/*'
      - .github/workflows/workflow.yml
      - 'package.psd1'

jobs:
  unittest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pester
        shell: pwsh
        run: |
          if (-not (Get-Module -ListAvailable -Name Pester)) {
              Install-Module -Name Pester -Force -SkipPublisherCheck
          }

      - name: Run Unit Tests
        shell: pwsh
        run: |
          Get-ChildItem -Path ".\UnitTests\" -Filter *.ps1 | ForEach-Object { . $_.FullName }

  build:
    runs-on: windows-latest
    needs: unittest  # Ensure the build job runs only after unittest job succeeds
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PowerShellProTools
        shell: pwsh
        run: |
          if (-not (Get-Module -ListAvailable -Name PowerShellProTools)) {
              Install-Module -Name PowerShellProTools -Force
          }
          Import-Module PowerShellProTools

      - name: Start Script Watcher
        shell: pwsh
        run: |
          .\Watch-ScriptsFolder.ps1

      - name: Build Executable
        shell: pwsh
        run: |
          Move-Item -Path "icon.ico" -Destination "C:\\icon.ico"
          Merge-Script -ConfigFile 'package.psd1' -Verbose   

      - name: Commit and Push Executable
        shell: pwsh
        run: |        
          if (Test-Path 'ScriptManager2.exe') {
              git config --global user.name "GitHub Action"
              git config --global user.email "action@github.com"
              git add ScriptManager2.exe
              git add ScriptManager2.ps1
              git commit -m "Add ScriptManager2.exe"
              git push || Write-Host "Failed to push changes"
          } else {
              Write-Host "Executable not found"
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
